name: Move Shortcut Story
description: Update the workflow state for all linked stories
inputs:
  GITHUB_TOKEN:
    required: true
    description: "Token to perform api calls"
  SHORTCUT_TOKEN:
    required: true
    description: "Token to perform api calls"
  workflowStateName:
    required: true
    description: "Desired workflow state"
  prNumbers:
    required: false
    description: "An optional newline seperated list of pr numbers to be moved. By default the context will be used."
    default: ""

runs:
  using: node12
  main: dist/index.js

branding:
  icon: 'message-square'
  color: 'blue'