name: Update PRs

on:
  push:
    branches:
      - main # update PR when base branch is updated

jobs:
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: merge
        uses: enosix/github-action-merge@v1.0.1
        with:
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
      - name: Move Merged Stories
        uses: enosix/github-action-shortcut-workflow-state@v1.0.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SHORTCUT_TOKEN: ${{secrets.CLUBHOUSE_TOKEN}}
          workflowStateName: "In Review"
          prNumbers: ${{ steps.merge.outputs.mergedPrNumbers }}
          stateWhitelist: "Ready For QA"
      - name: Move Conflicted Stories
        uses: enosix/github-action-shortcut-workflow-state@v1.0.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SHORTCUT_TOKEN: ${{secrets.CLUBHOUSE_TOKEN}}
          workflowStateName: "Awaiting changes"
          prNumbers: ${{ steps.merge.outputs.conflictedPrNumbers }}
          stateWhitelist: "Ready For QA"
